<application>
  <component name="AppStorage">
    <histories>
      <item value="16:17 Lombok Requires Annotation Processing Annotation processing seems to be disabled for the project &quot;PermissonManagementPlatForm&quot;. But lombok is on classpath. For the lombok plugin to function correctly, please enable it under &quot;Settings &gt; Build &gt; Compiler &gt; Annotation Processors&quot;" />
      <item value="Compilation completed successfully in 11 s 131 ms" />
      <item value="Lombok Requires Annotation Processing Annotation processing seems to be disabled for the project &quot;PermissonManagementPlatForm&quot;. But lombok is on classpath. For the lombok plugin to function correctly, please enable it under &quot;Settings &gt; Build &gt; Compiler &gt; Annotation Processors&quot;" />
      <item value="&quot;Settings &gt; Build &gt; Compiler &gt; Annotation Processors&quot;" />
      <item value="Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally. NOT STARTED. Currently in standby mode. Number of jobs executed: 0 Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads. Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered." />
      <item value="java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)" />
      <item value="Invocation of init method failed; nested exception is org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379" />
      <item value="org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysConfigController': Unsatisfied dependency expressed through field 'configService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysConfigServiceImpl': Invocation of init method failed; nested exception is org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379 at org.springframework.beans." />
      <item value="org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysConfigController': Unsatisfied dependency expressed through field 'configService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysConfigServiceImpl': Invocation of init method failed; nested exception is org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379" />
      <item value="### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLSyntaxErrorException: Unknown database 'ry-vue'" />
      <item value="15:17:41.008 [restartedMain] ERROR c.a.d.p.DruidDataSource - [init,922] - init datasource error, url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&amp;characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull&amp;useSSL=true&amp;serverTimezone=GMT%2B8 java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)" />
      <item value="SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5890cdf2] was not registered for synchronization because synchronization is not active Creating a new SqlSession" />
      <item value="Logging initialized using 'class org.apache.ibatis.logging.stdout.StdOutImpl' adapter." />
      <item value="org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'createtime' in 'class cn.lastwhisper.springbootwx.pojo.User'" />
      <item value="org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'openid' in 'class cn.lastwhisper.springbootwx.pojo.User'" />
      <item value="com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1" />
      <item value="Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1] with root cause com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1" />
      <item value="Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1] with root cause" />
      <item value="Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1" />
      <item value="Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1 ; Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1] with root cause" />
      <item value="## Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1 ; Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1] with root cause" />
      <item value="org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'createTime' in 'class java.lang.String'" />
      <item value="org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'createtime' in 'class java.lang.String'" />
      <item value="org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'create_time' in 'class java.lang.String'" />
      <item value="# Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1 ; Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'o4ZEB5eCDXGoF5VtMfOmj8uSNSGM' for column 'create_time' at row 1] with root cause" />
      <item value="org.apache.ibatis.binding.BindingException: Mapper method 'cn.lastwhisper.springbootwx.mapper.UserMapper.update' has an unsupported return type: class cn.lastwhisper.springbootwx.pojo.User" />
      <item value="org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'create_time' in 'class cn.lastwhisper.springbootwx.pojo.User'" />
      <item value="java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer" />
      <item value="java.lang.ClassCastException: java.util.HashMap cannot be cast to cn.lastwhisper.springbootwx.pojo.User at com.sun.proxy.$Proxy57.openid(Unknown Source) ~[na:na]" />
      <item value="org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userController': Unsatisfied dependency expressed through field 'userServer'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServer': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [G:\app\springboot-wx\target\classes\cn\lastwhisper\springbootwx\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [G:\app\springboot-wx\target\classes\mapper\UserMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'cn.lastwhisper.springbootwx.pojo'. Cause: java.lang.ClassNotFoundException: Cannot find class: cn.lastwhisper.springbootwx.pojo" />
      <item value="org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userController': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [G:\app\springboot-wx\target\classes\cn\lastwhisper\springbootwx\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [G:\app\springboot-wx\target\classes\mapper\UserMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'cn.lastwhisper.springbootwx.pojo'. Cause: java.lang.ClassNotFoundException: Cannot find class: cn.lastwhisper.springbootwx.pojo" />
      <item value="com.baomidou.mybatisplus.core.Mybatis Mapper Annotation Builder.get Language Driver(Mybatis Mapper Annotation Builder.java:369)" />
      <item value="Hoag FK Dcs GMVCIY 2 v Ojf 9 k LEI 86 zp Ua 6 Rw K 9 i Vraf 6 Eg Nt 1 soq Z e 4 U 5 r 3_5 V 1 gq P Tna Y FC 1 e F 1 jbd 27 to S Dg" />
      <item value="org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfigs], template might not exist or might not be accessible by any of the configured Template Resolvers" />
      <item value="Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfigs], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfigs], template might not exist or might not be accessible by any of the configured Template Resolvers" />
      <item value="七月 13, 2020 3:49:41 下午 org.apache.catalina.core.StandardWrapperValve invoke 严重: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfigs], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfigs], template might not exist or might not be accessible by any of the configured Template Resolvers" />
      <item value="Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfig], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfig], template might not exist or might not be accessible by any of the configured Template Resolvers" />
      <item value="org.apache.catalina.core.StandardWrapperValve invoke" />
      <item value="七月 13, 2020 10:10:16 上午 org.apache.catalina.core.StandardWrapperValve invoke 严重: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfig], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfig], template might not exist or might not be accessible by any of the configured Template Resolvers" />
      <item value="严重: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfig], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause org.thymeleaf.exceptions.TemplateInputException: Error resolving template [web/wxConfig/getWxConfig], template might not exist or might not be accessible by any of the configured Template Resolvers" />
      <item value="七月 09, 2020 10:07:21 上午 org.apache.catalina.core.StandardWrapperValve invoke 严重: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NumberFormatException: For input string: &quot;2020070800055&quot;] with root cause java.lang.NumberFormatException: For input string: &quot;2020070800055&quot;" />
      <item value="; bad SQL grammar []; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 对象名 'SBK_COPTD' 无效。] with root cause com.microsoft.sqlserver.jdbc.SQLServerException: 对象名 'SBK_COPTD' 无效。" />
      <item value="For more information about the errors and possible solutions, please read the following articles:" />
      <item value="SimpleDateFormat sdf1 = new SimpleDateFormat(&quot;yyyyMMdd&quot;); String time1 = sdf1.format(new Date()); String RC=&quot;rc&quot;; int s=(int)((Math.random()*9+1)*100000); private String excelserverrcid=RC+time1+s; public String getExcelserverrcid() { return excelserverrcid; } public void setExcelserverrcid(String excelserverrcid) { this.excelserverrcid = excelserverrcid; }" />
      <item value="java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [NonLoginAuthenticator[StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]] at java.util.concurrent.FutureTask.report(FutureTask.java:122) at java.util.concurrent.FutureTask.get(FutureTask.java:192)" />
      <item value="A child container failed during start" />
      <item value="Caused by: org.apache.catalina.LifecycleException: Failed to start component [NonLoginAuthenticator[StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]]" />
      <item value="Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.2.3:war (default-war) on project demo: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -&gt; [Help 1]" />
      <item value="[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.2.3:war (default-war) on project demo: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -&gt; [Help 1]" />
      <item value="For more information about the errors and possible solutions, please read the following articles" />
    </histories>
    <option name="languageScores">
      <map>
        <entry key="CHINESE" value="63" />
        <entry key="ENGLISH" value="68" />
      </map>
    </option>
  </component>
</application>